export const PATH = {
  HOME: "/home",
  ONBOARDING: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  PASSWORD_RESET: "/password-reset",
  MYPAGE: "/mypage",
  MYPAGE_DORMITORY: "/mypage/dormitory",
  ORDER_CHAT: "/orders/:orderId/chat",
  MYPAGE_SETTINGS: "/mypage/settings",
  MYPAGE_INQUIRY: "/mypage/inquiry",
  MYPAGE_PROFILE_EDIT: "/mypage/profile-edit",
  MYPAGE_ACCOUNT: "/mypage/account",
  MYPAGE_NOTIFICATIONS: "/mypage/notifications",
  MYPAGE_PASSWORD: "/mypage/password",
  MYPAGE_WITHDRAW: "/mypage/withdraw",
  ORDER_DETAIL: "/orders/:orderId",
  ORDER_REVIEW: "/orders/:orderId/review",
} as const;
