export const PATH = {
  HOME: "/home",
  ONBOARDING: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  PASSWORD_RESET: "/password-reset",
  MYPAGE: "/mypage",
  MYPAGE_DORMITORY: "/mypage/dormitory",
  ORDER_CHAT: "/orders/:orderId/chat",
  MYPAGE_SETTINGS: "/mypage/settings",
  MYPAGE_INQUIRY: "/mypage/inquiry",
  ORDER_DETAIL: "/orders/:orderId",
  ORDER_REVIEW: "/orders/:orderId/review",
  BOARD: "/board",
  BOARD_DETAIL: "/board/:postId",
  BOARD_CREATE: "/board/create",
} as const;
